r3/orm_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from main.views import cars_list_view, car_details_view, sales_by_car
from main.views import home_view, about_view, contacts_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', cars_list_view, name='list'),
    path('cars/<int:car_id>/', car_details_view, name='details'),
    path('cars/<int:car_id>/sales/', sales_by_car, name='sales'),

    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contacts/', contacts_view, name='contacts'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

r3/main/models.py
# verbose_name - отображение в админке
# choices - выбор из предопределенных значений
# Meta класс - настройки
# метод `__str__` для отображения, добавил id

from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(verbose_name='Дата рождения')
    phone_number = models.CharField(max_length=20, verbose_name='Телефон')

    def __str__(self):
        return f'{self.id} {self.name} {self.middle_name} {self.last_name}'


GEARBOX_CHOICES = (
    ('manual', 'Механика'),
    ('automatic', 'Автомат'),
    ('вариатор', 'CVT'),
    ('robot', 'Робот')
)

FUEL_TYPE_CHOICES = (
    ('gasoline', 'Бензин'),
    ('diesel', 'Дизель'),
    ('hybrid', 'Гибрид'),
    ('electro', 'Электро')
)

BODY_TYPE_CHOICES = (
    ('sedan', 'Седан'),
    ('hatchback', 'Хэтчбек'),
    ('SUV', 'Внедорожник'),
    ('wagon', 'Универсал'),
    ('minivan', 'Минивэн'),
    ('pickup', 'Пикап'),
    ('coupe', 'Купе'),
    ('cabrio', 'Кабриолет')
)


DRIVE_UNIT_CHOICES = (
    ('rear', 'Задний'),
    ('front', 'Передний'),
    ('full', 'Полный')
)


class Car(models.Model):
    model = models.CharField(max_length=100, verbose_name='Модель авто')
    year = models.PositiveIntegerField(verbose_name='Год выпуска')
    color = models.CharField(max_length=50, verbose_name='Цвет')
    mileage = models.PositiveIntegerField(verbose_name='Пробег')
    volume = models.DecimalField(max_digits=5, decimal_places=1, verbose_name='Объем двигателя')
    body_type = models.CharField(
        max_length=20,
        choices=BODY_TYPE_CHOICES,
        verbose_name='Тип кузова'
    )
    drive_unit = models.CharField(
        max_length=10,
        choices=DRIVE_UNIT_CHOICES,
        verbose_name='Привод'
    )
    gearbox = models.CharField(
        max_length=20,
        choices=GEARBOX_CHOICES,
        verbose_name='Коробка передач'
    )
    fuel_type = models.CharField(
        max_length=10,
        choices=FUEL_TYPE_CHOICES,
        verbose_name='Тип топлива'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Цена'
    )
    image = models.ImageField(
        upload_to='cars/',
        null=True,
        blank=True,
        verbose_name='Изображение авто'
    )

    def __str__(self):
        return f'{self.id} {self.model} {self.year} ({self.color})'

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'


class Sale(models.Model):
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        related_name='sales',
        verbose_name='Клиент'
    )
    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        related_name='sales',
        verbose_name='Автомобиль'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата продажи'
    )

    def __str__(self):
        return f'Продажа #{self.id} - {self.car} клиенту {self.client}'

    class Meta:
        verbose_name = 'Продажа'
        verbose_name_plural = 'Продажи'
        ordering = ['-created_at']

r3/main/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from main.models import Car, Sale


def cars_list_view(request):
    # список авто
    template_name = 'main/list.html'
    # поисковый запрос из GET-параметра 'q' указан в html шаблоне
    search_query = request.GET.get('q', '')

    if search_query:
        # поиск (без учета регистра)
        cars = Car.objects.filter(
            Q(model__icontains=search_query) |
            Q(color__icontains=search_query) |
            Q(year__icontains=search_query)
        ).order_by('-year', 'model')
    else:
        cars = Car.objects.all().order_by('-year', 'model')

    # Пагинация - 3 объекта на страницу
    page_number = request.GET.get('page', 1)
    paginator = Paginator(cars, 3)
    try:
        current_page = paginator.page(page_number)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
    # page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': current_page,
        'search_query': search_query
    }
    # без пагинации
    # context = {
    #     'cars': cars,
    #     'search_query': search_query  # Передаем запрос для отображения в форме
    # }

    return render(request, template_name, context)


def car_details_view(request, car_id):
    # получить объект, если его нет, ошибка 404
    template_name = 'main/details.html'
    car = get_object_or_404(Car, id=car_id)
    context = {
        'car': car,
    }
    return render(request, template_name, context)


def sales_by_car(request, car_id):
    try:
        # получение объекта авто и его продаж или 404
        template_name = 'main/sales.html'
        car = get_object_or_404(Car, id=car_id)
        sales = Sale.objects.filter(car=car).select_related('client').order_by('-created_at')

        paginator = Paginator(sales, 5)  # 5 на страницу
        page_number = request.GET.get('page')
        sales_page = paginator.get_page(page_number)

        context = {
            'car': car,
            'sales': sales_page
        }
        return render(request, template_name, context)

    except Car.DoesNotExist:
        raise Http404('Car not found')


def home_view(request):
    return render(request, 'main/home.html')

def about_view(request):
    return render(request, 'main/about.html')

def contacts_view(request):
    return render(request, 'main/contacts.html')

r3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
	<title>{% block title %}ORM Car showroom{% endblock title %}</title>

    <!-- общие -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- для страниц -->
    {% block meta %}
        <!-- Дефолтные мета-теги (если не переопределены в дочерних шаблонах) -->
        <meta name="description" content="Автосалон ORM Car - новые и подержанные автомобили">
        <meta property="og:title" content="ORM Car Showroom">
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}">
    	<meta name="keywords" content="">
    	<meta name="author" content="">
    {% endblock %}

<!--	<meta name="description" content="">  -->

    <!--  favicon -->
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'icon.png' %}">

    <!-- CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
</head>


<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

<!-- главное меню -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Заголовок и кнопка для мобильных -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">ORM Car Showroom</a>
    </div>

    <!-- Основное меню -->
    <div class="collapse navbar-collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
          <a href="{% url 'home' %}" style="padding-left: 25px; padding-right: 25px;">Главная</a>
        </li>
        <li class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
          <a href="{% url 'about' %}" style="padding-left: 25px; padding-right: 25px;">О нас</a>
        </li>
        <li class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">
          <a href="{% url 'contacts' %}" style="padding-left: 25px; padding-right: 25px;">Контакты</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


	{% block content %}
	{% endblock content %}

<!--	<footer id="footer">-->
<!--     <div class="container">-->
<!--     </div>-->
<!--	</footer>-->

<!-- футер -->
<footer class="bg-dark text-white py-5">
    <div class="container">
        <div class="row">
            <!-- 1 колонка -->
            <div class="col-md-6 mb-4">
                <h5>ORM Car Showroom</h5>
                <p class="text-muted">Лучшие автомобили по лучшим ценам с 1900 года</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-map-marker mr-2"></i> г. Автобаденбург, ул. Транспортная, 123</li>
                    <li><i class="fa fa-phone mr-2"></i> +7 (495) 123-45-67</li>
                    <li><i class="fa fa-envelope mr-2"></i> info@orm-car.test</li>
                </ul>
            </div>
            <!-- 2 колонка с меню -->
            <div class="col-md-3 mb-4">
                <h5>Меню</h5>
                <ul class="list-unstyled">
                    <li><a href="{% url 'home' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'list' %}" class="text-white">Каталог авто</a></li>
                    <li><a href="{% url 'about' %}" class="text-white">О компании</a></li>
                </ul>
            </div>
            <!-- 3 колонка с меню -->
            <div class="col-md-3 mb-4">
                <h5>Информация</h5>
                <ul class="list-unstyled">
                    <li><a href="{% url 'contacts' %}" class="text-white">Контакты</a></li>
                    <li><a href="#" class="text-white">Условия продажи</a></li>
                    <li><a href="#" class="text-white">Политика конфиденциальности</a></li>
                </ul>
            </div>
        </div>
        <hr class="bg-secondary">
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="mb-0">&copy; {% now "Y" %} ORM Car Showroom Автосалон. Все права защищены.</p>
            </div>
        </div>
    </div>
</footer>



	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/smoothscroll.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

r3/templates/main/about.html
{% extends 'base.html' %}
{% block meta %}
    {{ block.super }}
    <meta name="description" content="О нашем автосалоне ORM Car Showroom">
    <meta property="og:title" content="О нас | ORM Car Showroom">
{% endblock %}
{% block title %}О нас | ORM Car showroom{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="mb-4">О нашем автосалоне</h1>
                <p class="lead">ORM Car Showroom - это современный автомобильный салон со 100-летней историей.</p>
                
                <div class="row mt-5">
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h3><i class="fa fa-car"></i> Наш ассортимент</h3>
                                <p>Более 200 автомобилей в наличии от эконом до премиум класса. Lorem ipsum dolor
                                    sit amet, consectetur adipisicing elit. Distinctio explicabo facere facilis
                                    hic libero perferendis porro quia temporibus veniam voluptatem?</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h3><i class="fa fa-users"></i> Наша команда</h3>
                                <p>Профессиональные менеджеры с многолетним опытом работы. Lorem ipsum dolor
                                    sit amet, consectetur adipisicing elit. Distinctio explicabo facere facilis
                                    hic libero perferendis porro quia temporibus veniam voluptatem? </p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h3><i class="fa fa-certificate"></i> Наши преимущества</h3>
                                <p>Гарантия на все автомобили, помощь с кредитованием и страхованием. Lorem ipsum dolor
                                    sit amet, consectetur adipisicing elit. Distinctio explicabo facere facilis
                                    hic libero perferendis porro quia temporibus veniam voluptatem?</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

r3/templates/main/contacts.html
{% extends 'base.html' %}
{% block meta %}
    {{ block.super }}
    <meta name="description" content="Контакты автосалон ORM Car Showroom">
    <meta property="og:title" content="Контакты | ORM Car Showroom">
{% endblock %}
{% block title %}Контакты | ORM Car showroom{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mb-4">Наши контакты</h1>
                
                <div class="contact-info mb-5">
                    <h3><i class="fa fa-map-marker"></i> Адрес</h3>
                    <p>г. Автобаденбург, ул. Транспортная, д. 123</p>
                    
                    <h3 class="mt-4"><i class="fa fa-phone"></i> Телефоны</h3>
                    <p>+7 (123) 123-45-67 (основной)</p>
                    <p>+7 (321) 123-45-67 (мобильный)</p>
                    
                    <h3 class="mt-4"><i class="fa fa-envelope"></i> Email</h3>
                    <p>info@orm-car.test</p>
                    
                    <h3 class="mt-4"><i class="fa fa-clock-o"></i> Часы работы</h3>
                    <p>Пн-Пт: 9:00 - 21:00</p>
                    <p>Сб-Вс: 10:00 - 20:00</p>
                </div>
            </div>
            
            <div class="col-lg-6">
                <div class="map-container">
                <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A1a2b3c4d5e6f7g8h9i0j&amp;source=constructor"
                         width="100%" height="400" frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

r3/templates/main/details.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    {{ block.super }}  <!--  общие мета из base.html -->
    <meta name="description" content="Подробно об автомобиле {{ car.model }} {{ car.year }} года. Цена: {{ car.price }} руб.">
    <meta property="og:title" content="{{ car.model }} {{ car.year }} | ORM Car Showroom Автосалон">
    <meta property="og:description" content="Автомобиль {{ car.model }} {{ car.year }} года за {{ car.price }} руб.">
    {% if car.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ car.image.url }}">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
    {% endif %}
{% endblock %}
{% block title %}{{ car.model }}{% endblock title %}
{% block content %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <div>
<!--            <img src="{{ car.image.url }}" alt="" class="img-responsive wc-image">-->
              <img src="{% if car.image %}{{ car.image.url }}{% else %}{% static 'images/default-car.jpg' %}{% endif %}" alt="" class="img-responsive wc-image">

          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <h2>{{ car.model }}, {{ car.year }}</h2>
          <p class="lead">Цена: <strong class="text-primary">{{ car.price | floatformat:"-2g" }} ₽</strong></p>
          <div class="row">
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Модель</span>
                <br>
                <strong>{{ car.model }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Год выпуска</span>
                <br>
                <strong>{{ car.year }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Коробка передач</span>
                <br>
                <strong>{{ car.get_gearbox_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Привод</span>
                <br>
                <strong>{{ car.get_drive_unit_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Пробег</span>
                <br>
                <strong>{{ car.mileage }} км</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Топливо</span>
                <br>
                <strong>{{ car.get_fuel_type_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Объем двигателя</span>
                <br>
                <strong>{{ car.volume }} л</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Кузов</span>
                <br>
                <strong>{{ car.get_body_type_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Цвет</span>
                <br>
                <strong>{{ car.color }}</strong>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12 text-center">
            <a href="{% url 'list' %}" class="btn btn-default"> Назад к списку  </a>
        </div>
    </div>
    <br>
    <div class="row mt-4">
        <div class="col-md-12 text-center">
            <a href="{% url 'sales' car.id %}" class="btn btn-default"> Продажи  </a>
        </div>
    </div>

  </section>

{% endblock content %}

r3/templates/main/home.html
{% extends 'base.html' %}

{% block title %}Главная | ORM Car showroom{% endblock %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Автосалон ORM Car Showroom</h1>
        <p class="lead text-muted">Лучшие автомобили по лучшим ценам.</p>
        <p>
            <a href="{% url 'list' %}" class="btn btn-primary my-2">Посмотреть каталог</a>
            <a href="{% url 'contacts' %}" class="btn btn-secondary my-2">Связаться с нами</a>
        </p>
    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Широкий выбор</h5>
                    <p class="card-text">Более 200 автомобилей в наличии. Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit. Distinctio explicabo facere facilis hic libero perferendis porro quia
                        temporibus veniam voluptatem?</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Гарантия качества</h5>
                    <p class="card-text">Все автомобили проходят проверку. Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit. Distinctio explicabo facere facilis hic libero perferendis
                        porro quia temporibus veniam voluptatem?</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Индивидуальный подход</h5>
                    <p class="card-text">Подберем авто по вашим требованиям. Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit. Distinctio explicabo facere facilis hic libero perferendis
                        porro quia temporibus veniam voluptatem?</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

r3/templates/main/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список авто{% endblock title %}

{% block content %}
	<section>
		<div class="container">
			<div class="text-center">
				<h1>Список автомобилей</h1>
				<br>
				<div class="row">
					<div class="col-lg-6 col-xs-12 col-lg-offset-3">
						<div class="form">
							<form action="{% url 'list' %}" method="get">
								<div class="form-group">
									<label class="control-label">Поиск авто</label>
									<div class="input-group">
										<input type="text" class="form-control" placeholder="Mercedes ..." name="q">
										<span class="input-group-btn">
											<button class="btn btn-default" type="submit">Найти!</button>
										</span>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section-background">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-xs-12">

					<div class="row">
						{% for car in page_obj %}
							<div class="col-lg-4 col-md-4 col-sm-6">
							<div class="courses-thumb courses-thumb-secondary">
								<div class="courses-top">
									<div class="courses-image">
<!--	если нет картинки здесь err	<img src="{{ car.image.url }}" class="img-responsive" alt="">-->
 										<img src="{% if car.image %}{{ car.image.url }}{% else %}{% static 'images/default-car.jpg' %}{% endif %}" class="img-responsive" alt="">
									</div>
								</div>

								<div class="courses-detail">
<!--	здесь исправлена ссылка	-->
									<h3><a href="{% url 'details' car.id %}">{{ car.model }}</a></h3>
									<p class="lead">Цена: <strong>{{ car.price | floatformat:"-2g" }} ₽</strong></p>
									<p>{{ car.volume }} л. &nbsp;&nbsp;/&nbsp;&nbsp; {{ car.get_fuel_type_display }} &nbsp;&nbsp;/&nbsp;&nbsp; {{ car.year }} &nbsp;&nbsp;/&nbsp;&nbsp;
										{{ car.get_gearbox_display }}</p>
								</div>

								<div class="courses-info">
									<a href="{% url 'details' car.id %}" class="section-btn btn btn-primary btn-block">Подробнее</a>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>

				</div>
			</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="pagination">

									{% if page_obj.has_previous %}
										<li><a href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}">&laquo;</a></li>
										<li><a href="?page={{ page_obj.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">‹</a></li>
									{% endif %}

									{% for num in page_obj.paginator.page_range %}
										{% if page_obj.number == num %}
											<li class="active"><a href="#">{{ num }}</a></li>
										{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
											<li><a href="?page={{ num }}{% if search_query %}&q={{ search_query }}{% endif %}">{{ num }}</a></li>
										{% endif %}
									{% endfor %}

									{% if page_obj.has_next %}
										<li><a href="?page={{ page_obj.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">›</a></li>
										<li><a href="?page={{ page_obj.paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}">&raquo;</a></li>
									{% endif %}

								</ul>
							</div>
						</div>
		</div>
	</section>

{% endblock content %}

r3/templates/main/sales.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ car.model }}{% endblock title %}
{% block content %}
  <div class="container">
			<div class="text-center">
				<h1>{{ car.model }} {{ car.year }}</h1>
				<br>
      </div>
  </div>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
        <th scope="col">Номер телефона</th>
        <th scope="col">Дата продажи</th>
      </tr>
    </thead>
    <tbody>
      {% for sale in sales %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ sale.client.last_name }}</td>
          <td>{{ sale.client.name }}</td>
          <td>{{ sale.client.middle_name }}</td>
          <td>{{ sale.client.phone_number }}</td>
          <td>{{ sale.created_at|date:"d/m/Y" }} {{ sale.created_at|time:"H:i" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

<div class="pagination justify-content-center mt-4">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if sales.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ sales.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link">
                    Страница {{ sales.number }} из {{ sales.paginator.num_pages }}
                </span>
            </li>

            {% if sales.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ sales.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ sales.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

<div class="text-center mt-4">
    <a href="{% url 'details' car.id %}" class="btn btn-default">
        Назад в карточку автомобиля
    </a>
</div>

{% endblock content %}